### ISSUE TITLE
Manually request permissions (don't ask on page load)

### ISSUE THREAD

**Issue by msoechting** [TeamTetris/tetris-game#18]

**Comment by julianweise** [comment]
Unfortunately, it is not possible to use the [JavaScript Permission API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API) because it is in an experimental status (only partly supported by Chrome( and our TypeScript Compiler does not support it.

We could solve it by activating the required services (e.g.: location, camera) at a later point of time.

**Comment by msoechting** [comment]
Was this adressed in #46?

**Comment by Johannes-Schneider** [comment]
This was also part of the new UI enhancement.
But yes, it has been addressed.
